// ════════════════════════════════════════════════════════════
//  CENTRALIZED AI ERROR HANDLER
//  Single source of truth for all AI error classification,
//  user-facing messages, and retry decisions.
// ════════════════════════════════════════════════════════════

export type ErrorAction = 'retry' | 'stop' | 'skip' | 'auth_error';

export interface AIError {
  action:  ErrorAction;
  message: string;          // user-friendly UI message
  technical: string;        // for console/logging
}

/**
 * Classify an HTTP status code into an action.
 *   retry → try next model or next provider
 *   stop  → safety block / bad request — abort entirely
 *   skip  → no key for this provider — skip silently
 *   auth_error → invalid key — show settings link
 */
export function classifyStatus(status: number): ErrorAction {
  if (status === 400)              return 'stop';
  if (status === 401 || status === 403) return 'auth_error';
  if ([429, 500, 502, 503, 504].includes(status)) return 'retry';
  return 'retry'; // unknown — assume transient
}

/** Build a structured AIError from an HTTP response + provider name */
export function buildHttpError(status: number, provider: string, rawMsg?: string): AIError {
  const action = classifyStatus(status);

  const messages: Record<ErrorAction, string> = {
    stop:       `Request blocked by ${provider} safety policy. Please rephrase your input.`,
    auth_error: `Invalid API key for ${provider}. Check your keys in ⚙️ Settings.`,
    retry:      status === 429
                  ? `${provider} rate limit reached. Switching to backup…`
                  : `${provider} is temporarily busy. Trying next provider…`,
    skip:       `No API key for ${provider}. Skipping.`
  };

  return {
    action,
    message:   messages[action],
    technical: `${provider} HTTP ${status}: ${rawMsg || 'no detail'}`
  };
}

/** Build error from a caught JS exception */
export function buildExceptionError(err: unknown, provider: string): AIError {
  const msg = err instanceof Error ? err.message : String(err);

  if (msg.startsWith('SAFETY:')) {
    return {
      action:    'stop',
      message:   `Content blocked by ${provider}: ${msg.replace('SAFETY:', '')}`,
      technical: msg
    };
  }

  if (msg === 'NO_KEY' || msg.includes('NO_KEY')) {
    return {
      action:    'skip',
      message:   `No API key for ${provider}.`,
      technical: msg
    };
  }

  if (msg.includes('Failed to fetch') || msg.includes('NetworkError')) {
    return {
      action:    'retry',
      message:   `Network error reaching ${provider}. Trying backup…`,
      technical: msg
    };
  }

  return {
    action:    'retry',
    message:   `${provider} failed. Switching to backup…`,
    technical: msg
  };
}

/** User-friendly status messages for UI display */
export const STATUS_MESSAGES = {
  starting:       (p: string) => `Starting with ${p}…`,
  switching:      (from: string, to: string) => `${from} unavailable. Switching to ${to}…`,
  rateLimited:    (p: string) => `${p} rate limit reached. Trying backup…`,
  busy:           (p: string) => `${p} is busy. Switching provider…`,
  success:        (p: string) => `Generated by ${p}`,
  allFailed:      ()          => `All AI providers failed. Check your API keys in ⚙️ Settings.`,
  noKey:          ()          => `No API key configured. Add your free Gemini key in ⚙️ Settings.`,
  safetyBlock:    ()          => `Request blocked by AI safety filters. Please rephrase.`,
  imageGenStart:  ()          => `Starting image generation…`,
  imageTrying:    (p: string) => `Trying ${p} for image prompt generation…`,
  imageDescribe:  ()          => `Generating AI art prompts & description…`,
};
