// ════════════════════════════════════════════════════════════
//  IMAGE CREATOR PAGE — Uses dedicated imagePipeline
//  Shows actual image if generated, or detailed description
//  Real-time status: "Trying Gemini image → Trying Cloudflare…"
// ════════════════════════════════════════════════════════════
import { useState, useCallback } from 'react';
import { useApp } from '../../context/AppContext';
import { Auth } from '../../data/auth';
import { DB } from '../../data/db';
import { generateImageWithFallback } from '../../services/aiGateway';
import { getAnyKeyAvailable } from '../../services/aiGateway';
import { VoiceTextarea } from '../../components/common/VoiceInput';
import { TypingDots } from '../../components/common/TypingDots';
import { useToasts, ToastContainer } from '../../components/common/Toast';
import type { GenerationStatus } from '../../types';
import type { ImageResult } from '../../services/aiGateway/imagePipeline';
import { copyToClipboard } from '../../utils/helpers/clipboard';

export function ImageCreatorPage() {
  const { navigate, refresh } = useApp();
  const user = Auth.current();
  const { toasts, toast } = useToasts();

  const [prompt,  setPrompt]  = useState('');
  const [result,  setResult]  = useState<ImageResult | null>(null);
  const [running, setRunning] = useState(false);
  const [saved,   setSaved]   = useState(false);
  const [status,  setStatus]  = useState<GenerationStatus | null>(null);

  const handleVoice = useCallback((text: string) => setPrompt(text), []);

  const handleGenerate = async () => {
    if (!prompt.trim()) { toast('⚠️ Describe your image first.', 'error'); return; }
    if (!getAnyKeyAvailable()) { toast('⚙️ No API key — go to ⚙️ Settings.', 'error'); navigate('settings'); return; }

    setRunning(true); setResult(null); setSaved(false);
    setStatus({ message: 'Starting image generation…' });

    try {
      const res = await generateImageWithFallback(
        prompt.trim(),
        (s: GenerationStatus) => setStatus(s)
      );
      setResult(res);
      setStatus(null);
      toast(
        res.mode === 'generated'
          ? `🎨 Image generated by ${res.provider}!`
          : `📝 Image described by ${res.provider} (add more API keys for actual generation)`,
        'success'
      );
    } catch (err) {
      toast(`❌ ${err instanceof Error ? err.message : 'Image generation failed'}`, 'error');
      setStatus(null);
    } finally { setRunning(false); }
  };

  const handleSave = () => {
    if (!user || !result) return;
    if (DB.isDuplicate(user.id, prompt)) { toast('⚠️ This prompt already exists.', 'error'); return; }
    DB.add({
      userId: user.id, taskType: 'image',
      title: prompt.slice(0, 80) + (prompt.length > 80 ? '…' : ''),
      prompt, aiOutput: result.description,
      priority: '', dueDate: '', status: 'pending', provider: result.provider
    });
    refresh(); setSaved(true); toast('✅ Saved to Tasks!', 'success');
  };

  return (
    <>
      <ToastContainer toasts={toasts}/>
      <div className="page-header" style={{ marginBottom: 22 }}>
        <div style={{ display:'flex', alignItems:'center', gap:14 }}>
          <div style={{ width:52,height:52,borderRadius:14, background:'rgba(46,201,138,0.14)', border:'1px solid rgba(46,201,138,0.24)', display:'flex',alignItems:'center',justifyContent:'center',fontSize:26 }}>
            🎨
          </div>
          <div>
            <h2 style={{ color:'var(--accent3)' }}>Image Creator</h2>
            <p>Generate images or get detailed AI art prompts for any creative concept.</p>
          </div>
        </div>
      </div>

      <div className="create-task-layout">
        <div className="ct-card">
          <h3 style={{ color:'var(--accent3)' }}>🎨 Describe Your Image</h3>
          <VoiceTextarea label="Image description" value={prompt} onChange={setPrompt}
            placeholder="e.g. A futuristic city at night with neon lights, flying cars, and glowing holograms in a rainy cyberpunk style…"
            rows={5} disabled={running}/>
          <div style={{ display:'flex', gap:10, marginTop:16 }}>
            <button className="run-btn" onClick={handleGenerate} disabled={running||!prompt.trim()}
              style={{ flex:1, background:'linear-gradient(135deg,var(--accent3),#14916b)', boxShadow:'0 4px 18px rgba(46,201,138,0.3)' }}>
              {running ? <><TypingDots/>&nbsp;Generating…</> : <>🎨 Generate Image</>}
            </button>
            {(prompt||result) && <button className="btn btn-ghost" onClick={()=>{setPrompt('');setResult(null);setSaved(false);}}>✕</button>}
          </div>
          {running && status && (
            <div className="ai-status-feedback">
              <span className="ai-status-dot"/>
              <span>{status.message}</span>
              {status.provider && <span className="ai-badge" style={{fontSize:10}}>⚡ {status.provider}</span>}
            </div>
          )}
        </div>

        <div className="ct-tips">
          <h4>🎨 Image Tips</h4>
          <div className="tip-item"><span className="tip-num">1</span><span>Use 🎤 mic to describe your image by speaking.</span></div>
          <div className="tip-item"><span className="tip-num">2</span><span>Include <strong style={{color:'var(--text)'}}>style, mood, colors, lighting</strong> for best results.</span></div>
          <div className="tip-item"><span className="tip-num">3</span><span>The AI generates prompts ready for Midjourney, DALL-E 3, and Stable Diffusion.</span></div>
          <div className="tip-item"><span className="tip-num">4</span><span>Add Gemini, Cloudflare, or HuggingFace keys for actual image generation.</span></div>
          <div style={{marginTop:18,padding:14,background:'rgba(46,201,138,0.05)',border:'1px solid rgba(46,201,138,0.2)',borderRadius:12,fontSize:12}}>
            <div style={{fontWeight:700,color:'var(--accent3)',marginBottom:6}}>🎨 Image Pipeline</div>
            <div style={{color:'var(--text2)',lineHeight:1.8}}>
              1. Gemini image gen<br/>
              2. Cloudflare AI<br/>
              3. HuggingFace SD<br/>
              4. AI description fallback
            </div>
          </div>
        </div>
      </div>

      {/* Loading */}
      {running && status && (
        <div className="ai-live-output" style={{marginTop:22}}>
          <div className="ai-thinking">
            <div className="ai-loading-icon">🎨</div>
            <TypingDots/>
            <div className="thinking-text">{status.message}</div>
            {status.provider && <div className="thinking-sub">Using {status.provider}…</div>}
          </div>
        </div>
      )}

      {/* Result */}
      {result && !running && (
        <div className="image-result-box">
          <div style={{ display:'flex', alignItems:'center', justifyContent:'space-between', marginBottom:16, flexWrap:'wrap', gap:10 }}>
            <div className="ai-output-header-left">
              <span className="ai-badge">🤖 AI Generated</span>
              <span className="image-provider-tag">⚡ {result.provider}</span>
              <span className={`ai-badge ${result.mode==='generated'?'':'gemini'}`}>
                {result.mode==='generated'?'🖼️ Real Image':'📝 Art Prompts'}
              </span>
            </div>
            <div style={{display:'flex',gap:8}}>
              {user && <button className={`act-btn ${saved?'done':'run'}`} onClick={handleSave} disabled={saved}>{saved?'✅ Saved!':'💾 Save'}</button>}
              <button className="act-btn copy" onClick={()=>{copyToClipboard(result.description);toast('📋 Copied!','info');}}>📋 Copy</button>
              {result.imageUrl && (
                <a href={result.imageUrl} download="ai-generated-image.png" className="act-btn done" style={{textDecoration:'none'}}>
                  ⬇️ Download
                </a>
              )}
            </div>
          </div>

          {/* Actual generated image */}
          {result.imageUrl && (
            <div style={{marginBottom:20,textAlign:'center'}}>
              <img src={result.imageUrl} alt="AI Generated" style={{
                maxWidth:'100%', maxHeight:500, borderRadius:14,
                border:'1px solid var(--border2)',
                boxShadow:'0 8px 32px rgba(0,0,0,0.25)'
              }}/>
            </div>
          )}

          {/* Description / prompts */}
          <div className="ai-response-label">
            {result.mode==='generated' ? '📝 Image Details:' : '🎨 AI Art Prompts:'}
          </div>
          <div className="ai-response-text">{result.description}</div>
        </div>
      )}
    </>
  );
}
