// ════════════════════════════════════════════════════════════
//  IMAGE CREATOR PAGE
//  Pipeline: Cloudflare → HuggingFace → Gemini → text prompts
//  NEVER shows false "safety policy" for no-image responses
// ════════════════════════════════════════════════════════════
import { useState, useCallback } from 'react';
import { useApp } from '../../context/AppContext';
import { Auth } from '../../data/auth';
import { DB } from '../../data/db';
import { generateImageWithFallback } from '../../services/aiGateway';
import { getAnyKeyAvailable } from '../../services/aiGateway';
import { VoiceTextarea } from '../../components/common/VoiceInput';
import { TypingDots } from '../../components/common/TypingDots';
import { useToasts, ToastContainer } from '../../components/common/Toast';
import type { GenerationStatus } from '../../types';
import type { ImageResult } from '../../services/aiGateway/imagePipeline';

function copyText(t: string) {
  navigator.clipboard?.writeText(t).catch(() => {
    const el = document.createElement('textarea');
    el.value = t; document.body.appendChild(el); el.select();
    document.execCommand('copy'); document.body.removeChild(el);
  });
}

export function ImageCreatorPage() {
  const { refresh } = useApp();
  const user = Auth.current();
  const { toasts, toast } = useToasts();

  const [prompt,   setPrompt]   = useState('');
  const [result,   setResult]   = useState<ImageResult | null>(null);
  const [running,  setRunning]  = useState(false);
  const [saved,    setSaved]    = useState(false);
  const [status,   setStatus]   = useState<GenerationStatus | null>(null);
  const [imgError, setImgError] = useState('');

  const handleVoice = useCallback((text: string) => setPrompt(text), []);

  const handleGenerate = async () => {
    if (!prompt.trim()) { toast('⚠️ Please describe the image you want.', 'error'); return; }
    if (!getAnyKeyAvailable()) {
      toast('⚠️ No API key configured. Contact the developer.', 'error');
      return;
    }

    setRunning(true); setResult(null); setSaved(false);
    setImgError(''); setStatus({ message: 'Starting image generation…' });

    try {
      const res = await generateImageWithFallback(prompt.trim(), (s) => setStatus(s));
      setResult(res);
      setStatus(null);

      if (res.mode === 'generated' && res.imageUrl) {
        toast(`🎨 Image generated by ${res.provider}!`, 'success');
      } else {
        // Text description — NOT an error, just no image API configured
        toast('📝 AI art prompts generated! Add Cloudflare/HuggingFace key for real images.', 'info');
      }
    } catch (err) {
      // Only show "blocked" if it's an ACTUAL safety violation
      const msg = err instanceof Error ? err.message : 'Image generation failed';
      setImgError(msg);
      toast(`❌ ${msg}`, 'error');
      setStatus(null);
    } finally { setRunning(false); }
  };

  const handleSave = () => {
    if (!user || !result) return;
    if (DB.isDuplicate(user.id, prompt)) { toast('⚠️ Already saved.', 'error'); return; }
    DB.add({
      userId: user.id, taskType: 'image',
      title: prompt.slice(0, 80) + (prompt.length > 80 ? '…' : ''),
      prompt, aiOutput: result.description,
      priority: '', dueDate: '', status: 'pending', provider: result.provider
    });
    refresh(); setSaved(true); toast('✅ Saved to Tasks!', 'success');
  };

  return (
    <>
      <ToastContainer toasts={toasts}/>
      <div className="page-header" style={{ marginBottom: 22 }}>
        <div style={{ display:'flex', alignItems:'center', gap:14 }}>
          <div style={{ width:52, height:52, borderRadius:14, flexShrink:0, background:'rgba(46,201,138,0.16)', border:'1px solid rgba(46,201,138,0.3)', display:'flex', alignItems:'center', justifyContent:'center', fontSize:26 }}>
            🎨
          </div>
          <div>
            <h2 style={{ color:'var(--accent3)' }}>Image prompt Creator</h2>
            <p>Generate AI images prompt with Cloudflare SD or HuggingFace. Get art prompts for Midjourney & DALL-E.</p>
          </div>
        </div>
      </div>

      <div className="create-task-layout">
        <div className="ct-card">
          <h3 style={{ color:'var(--accent3)' }}>🎨 Describe Your Image</h3>

          <VoiceTextarea
            label="Describe your image"
            value={prompt}
            onChange={setPrompt}
            placeholder="e.g. A majestic lion standing on a cliff at sunset, golden hour lighting, photorealistic…"
            rows={5}
            disabled={running}
          />

          <div style={{ display:'flex', gap:10, marginTop:16 }}>
            <button
              className="run-btn"
              onClick={handleGenerate}
              disabled={running || !prompt.trim()}
              style={{ flex:1, background:'linear-gradient(135deg,var(--accent3),#14916b)', boxShadow:'0 4px 18px rgba(46,201,138,0.3)' }}
            >
              {running ? <><TypingDots/>&nbsp;Generating…</> : <>🎨 Generate Image</>}
            </button>
            {(prompt || result) && (
              <button className="btn btn-ghost" onClick={() => { setPrompt(''); setResult(null); setSaved(false); setImgError(''); }}>✕</button>
            )}
          </div>

          {running && status && (
            <div className="ai-status-feedback">
              <span className="ai-status-dot"/>
              <span>{status.message}</span>
              {status.provider && <span className="ai-badge" style={{ fontSize:10 }}>⚡ {status.provider}</span>}
            </div>
          )}

          {imgError && (
            <div style={{ marginTop:14, padding:'10px 14px', background:'rgba(241,107,107,0.1)', border:'1px solid rgba(241,107,107,0.3)', borderRadius:10, fontSize:13, color:'var(--danger)' }}>
              ⚠️ {imgError}
            </div>
          )}
        </div>

        <div className="ct-tips">
          <h4>🎨 Image Tips</h4>
          <div className="tip-item"><span className="tip-num">1</span><span>Use 🎤 mic to <strong style={{ color:'var(--text)' }}>speak</strong> your image idea.</span></div>
          <div className="tip-item"><span className="tip-num">2</span><span>Add <strong style={{ color:'var(--text)' }}>style, mood, lighting</strong> for better results.</span></div>
          <div className="tip-item"><span className="tip-num">3</span><span>If no image appears, you'll get <strong style={{ color:'var(--accent3)' }}>ready-to-use prompts</strong> for Midjourney & DALL-E.</span></div>
          <div className="tip-item"><span className="tip-num">4</span><span>Image pipeline: <strong>Cloudflare → HuggingFace → Gemini</strong></span></div>
          <div style={{ marginTop:18, padding:14, background:'rgba(46,201,138,0.05)', border:'1px solid rgba(46,201,138,0.2)', borderRadius:12, fontSize:12 }}>
            <div style={{ fontWeight:700, color:'var(--accent3)', marginBottom:6 }}>🖼️ Image Pipeline</div>
            <div style={{ color:'var(--text2)', lineHeight:1.8 }}>
              1. Cloudflare SD XL<br/>
              2. HuggingFace SD 2.1<br/>
              3. Gemini Image Gen<br/>
              4. AI Art Prompts
            </div>
          </div>
        </div>
      </div>

      {/* Loading state */}
      {running && status && (
        <div className="ai-live-output" style={{ marginTop:22 }}>
          <div className="ai-thinking">
            <div className="ai-loading-icon">🎨</div>
            <TypingDots/>
            <div className="thinking-text">{status.message}</div>
            {status.provider && <div className="thinking-sub">Using {status.provider}…</div>}
          </div>
        </div>
      )}

      {/* Result */}
      {result && !running && (
        <div className="ai-live-output" style={{ marginTop:22 }}>
          <div className="ai-output-header">
            <div className="ai-output-header-left">
              <span className="ai-badge">🤖 AI Generated</span>
              <span style={{
                display:'inline-flex', alignItems:'center', gap:5,
                padding:'3px 10px', borderRadius:100, fontSize:11, fontWeight:700,
                background: result.mode === 'generated' ? 'rgba(46,201,138,0.14)' : 'rgba(77,136,240,0.14)',
                color: result.mode === 'generated' ? 'var(--accent3)' : 'var(--accent-l)',
                border: `1px solid ${result.mode === 'generated' ? 'rgba(46,201,138,0.3)' : 'rgba(77,136,240,0.3)'}`
              }}>
                {result.mode === 'generated' ? '🖼️ Real Image' : '📝 Art Prompts'} — {result.provider}
              </span>
            </div>
            <div style={{ display:'flex', gap:8 }}>
              {user && (
                <button className={`act-btn ${saved ? 'done' : 'run'}`} onClick={handleSave} disabled={saved}>
                  {saved ? '✅ Saved!' : '💾 Save'}
                </button>
              )}
              <button className="act-btn copy" onClick={() => { copyText(result.description); toast('📋 Copied!', 'info'); }}>
                📋 Copy
              </button>
              {result.imageUrl && (
                <a href={result.imageUrl} download="ai-image.png" className="act-btn done" style={{ textDecoration:'none' }}>
                  ⬇️ Download
                </a>
              )}
            </div>
          </div>

          {/* Show actual generated image */}
          {result.imageUrl && (
            <div style={{ textAlign:'center', marginBottom:18 }}>
              <img
                src={result.imageUrl}
                alt="AI Generated"
                style={{ maxWidth:'100%', maxHeight:520, borderRadius:14, border:'1px solid var(--border2)', boxShadow:'0 8px 32px rgba(0,0,0,0.2)' }}
              />
            </div>
          )}

          {/* Description / prompts */}
          <div className="ai-response-label">
            {result.mode === 'generated' ? '📝 About this image:' : '🎨 AI Art Prompts:'}
          </div>
          <div className="ai-response-text">{result.description}</div>
        </div>
      )}
    </>
  );
}
