// ════════════════════════════════════════════════════════════
//  TOOL PAGE — Shared template for 9 text-based AI tools
//  ImageCreator has its own dedicated page.
//  All tools include voice input.
// ════════════════════════════════════════════════════════════
import { useState, useCallback } from 'react';
import type { TaskType, GenerationStatus } from '../../types';
import type { ToolConfig } from '../../utils/helpers';
import { TOOL_COLOR_CLASSES } from '../../utils/helpers';
import { VoiceTextarea } from '../../components/common/VoiceInput';
import { TypingDots } from '../../components/common/TypingDots';
import { useApp } from '../../context/AppContext';
import { Auth } from '../../data/auth';
import { DB } from '../../data/db';
import { generateTextWithFallback, getAnyKeyAvailable } from '../../services/aiGateway';
import { useToasts, ToastContainer } from '../../components/common/Toast';

interface ToolPageProps { config: ToolConfig; }

function copyToClipboard(text: string) {
  navigator.clipboard?.writeText(text).catch(() => {
    const el = document.createElement('textarea');
    el.value = text; document.body.appendChild(el); el.select();
    document.execCommand('copy'); document.body.removeChild(el);
  });
}

export function ToolPage({ config }: ToolPageProps) {
  const { navigate, refresh } = useApp();
  const user = Auth.current();
  const { toasts, toast } = useToasts();
  const colors = TOOL_COLOR_CLASSES[config.color] || TOOL_COLOR_CLASSES.blue;

  const [input,   setInput]   = useState('');
  const [output,  setOutput]  = useState('');
  const [running, setRunning] = useState(false);
  const [saved,   setSaved]   = useState(false);
  const [status,  setStatus]  = useState<GenerationStatus | null>(null);
  const [provider,setProvider]= useState('');

  const handleVoice = useCallback((text: string) => setInput(text), []);

  const handleGenerate = async () => {
    if (!input.trim()) { toast('⚠️ Enter or speak your request first.', 'error'); return; }
    if (!getAnyKeyAvailable()) { toast('⚙️ No API key. Go to ⚙️ Settings.', 'error'); navigate('tools'); return; }

    setRunning(true); setOutput(''); setSaved(false); setStatus({ message: 'Starting AI…' });

    try {
      const { text, provider: prov } = await generateTextWithFallback(
        input.trim(), config.id as TaskType,
        (s: GenerationStatus) => setStatus(s)
      );
      setOutput(text); setProvider(prov); setStatus(null);
      toast(`✅ Generated by ${prov}!`, 'success');
    } catch (err) {
      toast(`❌ ${err instanceof Error ? err.message : 'Generation failed'}`, 'error');
      setStatus(null);
    } finally { setRunning(false); }
  };

  const handleSave = () => {
    if (!user || !output) return;
    if (DB.isDuplicate(user.id, input)) { toast('⚠️ This prompt already exists.', 'error'); return; }
    DB.add({ userId:user.id, taskType:config.id as TaskType, title:input.slice(0,80)+(input.length>80?'…':''),
      prompt:input, aiOutput:output, priority:'', dueDate:'', status:'pending', provider });
    refresh(); setSaved(true); toast('✅ Saved to Tasks!', 'success');
  };

  return (
    <>
      <ToastContainer toasts={toasts}/>
      <div className="page-header" style={{ marginBottom: 22 }}>
        <div style={{ display:'flex', alignItems:'center', gap:14 }}>
          <div style={{ width:52,height:52,borderRadius:14,flexShrink:0, background:colors.bg,border:`1px solid ${colors.border}`,display:'flex',alignItems:'center',justifyContent:'center',fontSize:26 }}>
            {config.icon}
          </div>
          <div>
            <h2 style={{ color:colors.text }}>{config.name}</h2>
            <p>{config.description}</p>
          </div>
        </div>
      </div>

      <div className="create-task-layout">
        <div className="ct-card">
          <h3 style={{ color:colors.text }}>{config.icon} {config.inputLabel}</h3>
          <VoiceTextarea label={config.inputLabel} value={input} onChange={setInput}
            placeholder={config.inputPlaceholder} rows={6} disabled={running}/>
          <div style={{ display:'flex', gap:10, marginTop:18 }}>
            <button className="run-btn" onClick={handleGenerate} disabled={running||!input.trim()}
              style={{ flex:1, background:`linear-gradient(135deg,${colors.text},${colors.border})`, boxShadow:`0 4px 18px ${colors.bg}` }}>
              {running ? <><TypingDots/>&nbsp;Generating…</> : <>{config.icon} Generate</>}
            </button>
            {(input||output) && <button className="btn btn-ghost" onClick={()=>{setInput('');setOutput('');setSaved(false);}} title="Clear">✕</button>}
          </div>
          {running && status && (
            <div className="ai-status-feedback">
              <span className="ai-status-dot"/>
              <span>{status.message}</span>
              {status.provider && <span className="ai-badge" style={{fontSize:10}}>⚡ {status.provider}</span>}
            </div>
          )}
        </div>

        <div className="ct-tips">
          <h4>💡 Tips for {config.shortName}</h4>
          <div className="tip-item"><span className="tip-num">1</span><span>Use 🎤 mic to <strong style={{color:'var(--text)'}}>speak</strong> your request instead of typing.</span></div>
          <div className="tip-item"><span className="tip-num">2</span><span>Be specific — more detail = better AI output.</span></div>
          <div className="tip-item"><span className="tip-num">3</span><span><strong style={{color:colors.text}}>Save to Tasks</strong> to keep the output for later.</span></div>
          <div className="tip-item"><span className="tip-num">4</span><span>AI auto-switches providers if one is busy.</span></div>
          <div style={{marginTop:18,padding:14,background:'rgba(77,136,240,0.06)',border:'1px solid var(--border)',borderRadius:12,fontSize:12}}>
            <div style={{fontWeight:700,color:colors.text,marginBottom:6}}>🔁 Fallback Chain</div>
            <div style={{color:'var(--text2)',lineHeight:1.7}}>Groq → Gemini → OpenRouter<br/>→ Cloudflare → HuggingFace</div>
          </div>
        </div>
      </div>

      {running && status && (
        <div className="ai-live-output" style={{marginTop:22}}>
          <div className="ai-thinking">
            <div className="ai-loading-icon">{config.icon}</div>
            <TypingDots/>
            <div className="thinking-text">{status.message}</div>
            {status.provider && <div className="thinking-sub">Using {status.provider}…</div>}
          </div>
        </div>
      )}

      {output && !running && (
        <div className="ai-live-output" style={{marginTop:22}}>
          <div className="ai-output-header">
            <div className="ai-output-header-left">
              <span className="ai-badge">🤖 AI Generated</span>
              <span className="ai-badge gemini">✨ {provider}</span>
            </div>
            <div style={{display:'flex',gap:8}}>
              {user && <button className={`act-btn ${saved?'done':'run'}`} onClick={handleSave} disabled={saved}>{saved?'✅ Saved!':'💾 Save'}</button>}
              <button className="act-btn copy" onClick={()=>{copyToClipboard(output);toast('📋 Copied!','info');}}>📋 Copy</button>
            </div>
          </div>
          <div className="ai-response-label">⚡ {config.outputLabel}:</div>
          <div className="ai-response-text">{output}</div>
        </div>
      )}
    </>
  );
}
