// ════════════════════════════════════════════════════════════
//  IMAGE PIPELINE — generateImageWithFallback(prompt)
//  Dedicated pipeline: SEPARATE from text system.
//
//  Priority:
//  1. Gemini image generation models (with key rotation)
//  2. Cloudflare AI (image models)
//  3. HuggingFace (Stable Diffusion)
//  4. OpenRouter (describe image as text fallback)
//
//  Output: { success, imageUrl, description, provider, mode, meta }
//  - imageUrl: base64 data URL if generated, null if text-only
//  - description: always present (either image desc or AI text)
//
//  Error handling:
//  - 400 → STOP (safety/invalid input)
//  - 429/500/503 → retry / fallback
//  - Circuit breaker: disable provider for 60s after failure
//  - Backoff: 800-1200ms ±300ms jitter between providers
// ════════════════════════════════════════════════════════════
import {
  hasGemini, hasCloudflare, hasHuggingFace, hasOpenRouter, hasGroq,
  getGeminiKeys, getCloudflareKey, getCFAccountId, getHFKey, getOpenRouterKey, getGroqKey,
  rotateKey, backoff, classifyError, disableKey
} from './providerManager';
import { isOpen, recordFailure, recordSuccess } from './circuitBreaker';
import {
  GEMINI_IMAGE_MODELS, GEMINI_BASE, formatImageRequest,
  extractImageData, extractText as geminiExtractText
} from '../../utils/aiAdapters/geminiAdapter';
import { classifyHttpStatus, getUserMessage, getFailMessage } from '../../utils/helpers/aiErrorHandler';
import type { GenerationStatus } from '../../types';

export type OnImageStatus = (s: GenerationStatus) => void;

export interface ImageResult {
  success:     boolean;
  imageUrl:    string | null;   // data:image/... base64 OR null if text-only
  description: string;          // text description / AI art prompts
  provider:    string;
  mode:        'generated' | 'described';
  meta: {
    model?: string;
    attempts?: number;
    fallbackChain?: string[];
  };
}

// ── 1. Gemini image generation ────────────────────────────
async function tryGeminiImage(prompt: string, onStatus: OnImageStatus): Promise<ImageResult | null> {
  const keys = getGeminiKeys();
  if (!keys.length) return null;

  for (let mi = 0; mi < GEMINI_IMAGE_MODELS.length; mi++) {
    const model = GEMINI_IMAGE_MODELS[mi];
    const key = rotateKey(keys, 'Gemini-Image');

    // Add backoff between model attempts (not on first)
    if (mi > 0) await backoff();

    onStatus({ message: `Trying Gemini image (${model})…`, provider: 'Gemini' });

    try {
      const res = await fetch(`${GEMINI_BASE}/${model}:generateContent?key=${key}`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(formatImageRequest(prompt))
      });

      if (!res.ok) {
        const status = res.status;
        const action = classifyHttpStatus(status);

        // 400 = safety block → STOP immediately
        if (action === 'stop') {
          throw new Error('SAFETY:Image blocked by safety policy');
        }

        // 429 = rate limit → disable this key, try next model
        if (status === 429) {
          disableKey(key);
          onStatus({ message: getUserMessage('rate_limited'), provider: 'Gemini' });
          continue;
        }

        // 500/503 = server error → try next model
        if (action === 'retry') {
          onStatus({ message: getFailMessage('Gemini', `${model} unavailable`), provider: 'Gemini' });
          continue;
        }

        continue; // other errors → try next model
      }

      const data = await res.json();
      const imgUrl  = extractImageData(data);
      const textDesc = (() => { try { return geminiExtractText(data); } catch { return ''; } })();

      if (imgUrl) {
        recordSuccess('Gemini');
        return {
          success: true, imageUrl: imgUrl,
          description: textDesc || 'Image generated by Gemini AI',
          provider: 'Gemini', mode: 'generated',
          meta: { model }
        };
      }

      if (textDesc) {
        recordSuccess('Gemini');
        return {
          success: true, imageUrl: null,
          description: textDesc,
          provider: 'Gemini', mode: 'described',
          meta: { model }
        };
      }
    } catch (err) {
      if (err instanceof Error && err.message.startsWith('SAFETY:')) throw err;
      // Continue to next model
    }
  }
  return null;
}

// ── 2. Cloudflare image generation ───────────────────────
async function tryCloudflareImage(prompt: string, onStatus: OnImageStatus): Promise<ImageResult | null> {
  const key = getCloudflareKey(); const accountId = getCFAccountId();
  if (!key || !accountId) return null;

  onStatus({ message: 'Trying Cloudflare image generation…', provider: 'Cloudflare AI' });

  const CF_IMAGE_MODELS = [
    '@cf/stabilityai/stable-diffusion-xl-base-1.0',
    '@cf/runwayml/stable-diffusion-v1-5-inpainting'
  ];

  for (const model of CF_IMAGE_MODELS) {
    try {
      const res = await fetch(
        `https://api.cloudflare.com/client/v4/accounts/${accountId}/ai/run/${model}`,
        {
          method: 'POST',
          headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${key}` },
          body: JSON.stringify({ prompt, num_steps: 20, guidance: 7.5 })
        }
      );

      if (!res.ok) {
        const action = classifyHttpStatus(res.status);
        if (action === 'stop') throw new Error('SAFETY:Image blocked by Cloudflare');
        if (action === 'retry') {
          onStatus({ message: getFailMessage('Cloudflare AI', `Model ${model.split('/').pop()} busy`), provider: 'Cloudflare AI' });
          continue;
        }
        continue;
      }

      const blob = await res.blob();
      const reader = new FileReader();
      const dataUrl = await new Promise<string>((resolve, reject) => {
        reader.onload  = () => resolve(reader.result as string);
        reader.onerror = reject;
        reader.readAsDataURL(blob);
      });
      recordSuccess('Cloudflare AI');
      return {
        success: true, imageUrl: dataUrl,
        description: `Image generated by Cloudflare AI (${model.split('/').pop()})`,
        provider: 'Cloudflare AI', mode: 'generated',
        meta: { model }
      };
    } catch (err) {
      if (err instanceof Error && err.message.startsWith('SAFETY:')) throw err;
      recordFailure('Cloudflare AI');
      /* try next model */
    }
  }
  return null;
}

// ── 3. HuggingFace Stable Diffusion ──────────────────────
async function tryHuggingFaceImage(prompt: string, onStatus: OnImageStatus): Promise<ImageResult | null> {
  const key = getHFKey();
  if (!key) return null;

  onStatus({ message: 'Trying HuggingFace Stable Diffusion…', provider: 'HuggingFace' });

  const HF_IMAGE_MODELS = [
    'stabilityai/stable-diffusion-2-1',
    'runwayml/stable-diffusion-v1-5'
  ];

  for (const model of HF_IMAGE_MODELS) {
    try {
      const res = await fetch(`https://api-inference.huggingface.co/models/${model}`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${key}` },
        body: JSON.stringify({ inputs: prompt, options: { wait_for_model: true } })
      });

      if (!res.ok) {
        const action = classifyHttpStatus(res.status);
        if (action === 'stop') throw new Error('SAFETY:Image blocked by HuggingFace');
        if (action === 'retry') {
          onStatus({ message: getFailMessage('HuggingFace', `${model.split('/').pop()} busy`), provider: 'HuggingFace' });
          continue;
        }
        continue;
      }

      const blob = await res.blob();
      if (blob.type.startsWith('image/')) {
        const reader = new FileReader();
        const dataUrl = await new Promise<string>((resolve, reject) => {
          reader.onload  = () => resolve(reader.result as string);
          reader.onerror = reject;
          reader.readAsDataURL(blob);
        });
        recordSuccess('HuggingFace');
        return {
          success: true, imageUrl: dataUrl,
          description: `Stable Diffusion image for: ${prompt}`,
          provider: 'HuggingFace', mode: 'generated',
          meta: { model }
        };
      }
    } catch (err) {
      if (err instanceof Error && err.message.startsWith('SAFETY:')) throw err;
      recordFailure('HuggingFace');
      /* try next model */
    }
  }
  return null;
}

// ── 4. Fallback: describe the image via text AI ───────────
async function describeImageAsText(prompt: string, onStatus: OnImageStatus): Promise<ImageResult> {
  const orKey = getOpenRouterKey();
  onStatus({ message: 'Generating image description & prompts…', provider: 'AI Description' });

  const descPrompt = `You are an expert AI art director. For the following image request, provide:
1. A vivid, detailed description of the image (colors, composition, lighting, mood)
2. An optimized Midjourney prompt (start with /imagine)
3. An optimized DALL-E 3 prompt
4. An optimized Stable Diffusion prompt

Image request: ${prompt}`;

  if (orKey) {
    try {
      const res = await fetch('https://openrouter.ai/api/v1/chat/completions', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${orKey}`,
          'HTTP-Referer': 'https://smart-ai-assistant.app', 'X-Title': 'Smart AI Assistant' },
        body: JSON.stringify({
          model: 'meta-llama/llama-3.1-8b-instruct:free',
          messages: [{ role: 'user', content: descPrompt }],
          max_tokens: 1000
        })
      });
      if (res.ok) {
        const data = await res.json() as { choices?: Array<{ message?: { content?: string } }> };
        const text = data?.choices?.[0]?.message?.content?.trim();
        if (text) return {
          success: true, imageUrl: null, description: text,
          provider: 'OpenRouter (Text)', mode: 'described',
          meta: { model: 'llama-3.1-8b-instruct' }
        };
      }
    } catch { /* fall through */ }
  }

  // Try Gemini text fallback
  const geminiKeys = getGeminiKeys();
  if (geminiKeys.length) {
    try {
      const key = rotateKey(geminiKeys, 'Gemini-Desc');
      const res = await fetch(`${GEMINI_BASE}/gemini-2.0-flash:generateContent?key=${key}`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          contents: [{ parts: [{ text: descPrompt }] }],
          generationConfig: { temperature: 0.8, maxOutputTokens: 1000 }
        })
      });
      if (res.ok) {
        const data = await res.json();
        const text = geminiExtractText(data);
        if (text) return {
          success: true, imageUrl: null, description: text,
          provider: 'Gemini (Text)', mode: 'described',
          meta: { model: 'gemini-2.0-flash' }
        };
      }
    } catch { /* fall through */ }
  }

  // Try Groq text fallback
  const groqKey = getGroqKey();
  if (groqKey) {
    try {
      const res = await fetch('https://api.groq.com/openai/v1/chat/completions', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${groqKey}` },
        body: JSON.stringify({
          model: 'llama-3.3-70b-versatile',
          messages: [{ role: 'user', content: descPrompt }],
          max_tokens: 1000
        })
      });
      if (res.ok) {
        const data = await res.json() as { choices?: Array<{ message?: { content?: string } }> };
        const text = data?.choices?.[0]?.message?.content?.trim();
        if (text) return {
          success: true, imageUrl: null, description: text,
          provider: 'Groq (Text)', mode: 'described',
          meta: { model: 'llama-3.3-70b-versatile' }
        };
      }
    } catch { /* fall through */ }
  }

  // Absolute fallback — built-in response
  return {
    success: true,
    imageUrl: null,
    description: `Image Description for: "${prompt}"\n\nTo generate this image, use these prompts:\n\n🎨 Midjourney: /imagine prompt: ${prompt}, highly detailed, 8k, professional photography, cinematic lighting\n\n🖼️ DALL-E 3: Create a high-quality, detailed image of ${prompt} in a realistic style with professional lighting\n\n⚙️ Stable Diffusion: ${prompt}, masterpiece, best quality, ultra detailed, photorealistic\n\n💡 Tip: Add your Gemini, Cloudflare, or HuggingFace API key in Settings for actual image generation.`,
    provider: 'Built-in Fallback',
    mode:     'described',
    meta: {}
  };
}

// ── Main export ───────────────────────────────────────────
export async function generateImageWithFallback(
  prompt:   string,
  onStatus: OnImageStatus = () => {}
): Promise<ImageResult> {

  const attemptedProviders: string[] = [];

  // Pipeline: Gemini → Cloudflare → HuggingFace → Text Fallback
  const pipeline: Array<{ name: string; fn: () => Promise<ImageResult | null> }> = [
    {
      name: 'Gemini',
      fn: () => hasGemini() && !isOpen('Gemini') ? tryGeminiImage(prompt, onStatus) : Promise.resolve(null)
    },
    {
      name: 'Cloudflare AI',
      fn: () => hasCloudflare() && !isOpen('Cloudflare AI') ? tryCloudflareImage(prompt, onStatus) : Promise.resolve(null)
    },
    {
      name: 'HuggingFace',
      fn: () => hasHuggingFace() && !isOpen('HuggingFace') ? tryHuggingFaceImage(prompt, onStatus) : Promise.resolve(null)
    }
  ];

  for (let i = 0; i < pipeline.length; i++) {
    const { name, fn } = pipeline[i];

    // Backoff between provider switches (not on first)
    if (i > 0) {
      onStatus({ message: getUserMessage('switching'), provider: name });
      await backoff();
    }

    try {
      attemptedProviders.push(name);
      const result = await fn();
      if (result) {
        result.meta.attempts = i + 1;
        result.meta.fallbackChain = attemptedProviders;
        return result;
      }
    } catch (err) {
      if (err instanceof Error && err.message.startsWith('SAFETY:')) {
        throw new Error(err.message.replace('SAFETY:', ''));
      }
      recordFailure(name);
      onStatus({ message: getFailMessage(name), provider: name });
    }
  }

  // All image providers failed or unavailable — use text description
  onStatus({ message: 'All image providers exhausted. Generating text description…', provider: 'Text AI' });
  const textResult = await describeImageAsText(prompt, onStatus);
  textResult.meta.attempts = pipeline.length + 1;
  textResult.meta.fallbackChain = [...attemptedProviders, 'Text Fallback'];
  return textResult;
}
