// ════════════════════════════════════════════════════════════
//  IMAGE PIPELINE  —  Cloudflare → HuggingFace → Gemini text
//  FIXES:
//  ✅ Cloudflare first (most reliable for actual images)
//  ✅ NEVER shows false "safety policy" for no-image response
//  ✅ imageUrl:null returns mode:'described', not an error
//  ✅ Proper success/failure distinction
// ════════════════════════════════════════════════════════════
import {
  hasGemini, hasCloudflare, hasHuggingFace,
  getGeminiKeys, getCloudflareKey, getCFAccountId, getHFKey,
  rotateKey, exhaustKey, backoff, modelBackoff
} from './providerManager';
import { isOpen, recordFailure, recordSuccess } from './circuitBreaker';
import { classifyStatus } from '../../utils/helpers/aiErrorHandler';
import {
  GEMINI_BASE, formatImageRequest,
  extractImageData, extractImageText
} from '../../utils/aiAdapters/geminiAdapter';
import type { GenerationStatus } from '../../types';

export type OnImageStatus = (s: GenerationStatus) => void;

export interface ImageResult {
  success:     boolean;
  imageUrl:    string | null;
  description: string;
  provider:    string;
  mode:        'generated' | 'described';
  meta:        Record<string, unknown>;
}

// ── blob → data URL ─────────────────────────────────────
async function blobToDataUrl(blob: Blob): Promise<string> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onload  = () => resolve(reader.result as string);
    reader.onerror = () => reject(new Error('FileReader failed'));
    reader.readAsDataURL(blob);
  });
}

// ── 1. CLOUDFLARE (primary — most reliable) ──────────────
async function tryCloudflareImage(prompt: string, onStatus: OnImageStatus): Promise<ImageResult | null> {
  const key = getCloudflareKey();
  const accountId = getCFAccountId();
  if (!key || !accountId) return null;
  if (isOpen('Cloudflare AI')) return null;

  const MODELS = [
    '@cf/stabilityai/stable-diffusion-xl-base-1.0',
    '@cf/lykon/dreamshaper-8-lcm',
    '@cf/runwayml/stable-diffusion-v1-5-inpainting'
  ];

  for (let i = 0; i < MODELS.length; i++) {
    if (i > 0) await modelBackoff();
    const model = MODELS[i];
    onStatus({ message: `Generating with Cloudflare AI (${model.split('/').pop()})…`, provider: 'Cloudflare AI' });

    try {
      const res = await fetch(
        `https://api.cloudflare.com/client/v4/accounts/${accountId}/ai/run/${model}`,
        {
          method: 'POST',
          headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${key}` },
          body: JSON.stringify({ prompt, num_steps: 20, guidance: 7.5, width: 512, height: 512 })
        }
      );

      if (!res.ok) {
        const action = classifyStatus(res.status);
        if (action === 'stop') throw new Error('SAFETY:Cloudflare blocked this prompt');
        continue; // try next model
      }

      const blob = await res.blob();
      if (blob.type.startsWith('image/') && blob.size > 1000) {
        const dataUrl = await blobToDataUrl(blob);
        recordSuccess('Cloudflare AI');
        return {
          success: true, imageUrl: dataUrl,
          description: `Image generated by Cloudflare AI (${model.split('/').pop()})`,
          provider: 'Cloudflare AI', mode: 'generated',
          meta: { model, size: blob.size }
        };
      }
      // blob wasn't an image → try next model
    } catch (err) {
      const msg = err instanceof Error ? err.message : '';
      if (msg.startsWith('SAFETY:')) throw err;
      // network or other error → try next model
    }
  }

  recordFailure('Cloudflare AI');
  return null;
}

// ── 2. HUGGING FACE Stable Diffusion ─────────────────────
async function tryHuggingFaceImage(prompt: string, onStatus: OnImageStatus): Promise<ImageResult | null> {
  const key = getHFKey();
  if (!key) return null;
  if (isOpen('HuggingFace')) return null;

  const MODELS = [
    'stabilityai/stable-diffusion-2-1',
    'runwayml/stable-diffusion-v1-5',
    'CompVis/stable-diffusion-v1-4'
  ];

  for (let i = 0; i < MODELS.length; i++) {
    if (i > 0) await modelBackoff();
    const model = MODELS[i];
    onStatus({ message: `Generating with HuggingFace (${model.split('/').pop()})…`, provider: 'HuggingFace' });

    try {
      const res = await fetch(`https://api-inference.huggingface.co/models/${model}`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${key}` },
        body: JSON.stringify({ inputs: prompt, options: { wait_for_model: true } })
      });

      if (!res.ok) {
        const action = classifyStatus(res.status);
        if (action === 'stop') throw new Error('SAFETY:HuggingFace blocked this prompt');
        continue;
      }

      const blob = await res.blob();
      if (blob.type.startsWith('image/') && blob.size > 1000) {
        const dataUrl = await blobToDataUrl(blob);
        recordSuccess('HuggingFace');
        return {
          success: true, imageUrl: dataUrl,
          description: `Stable Diffusion image for: ${prompt.slice(0, 60)}`,
          provider: 'HuggingFace', mode: 'generated',
          meta: { model }
        };
      }
    } catch (err) {
      const msg = err instanceof Error ? err.message : '';
      if (msg.startsWith('SAFETY:')) throw err;
    }
  }

  recordFailure('HuggingFace');
  return null;
}

// ── 3. GEMINI image gen (free tier — often returns text only) ─
async function tryGeminiImage(prompt: string, onStatus: OnImageStatus): Promise<ImageResult | null> {
  const keys = getGeminiKeys();
  if (!keys.length) return null;
  if (isOpen('Gemini')) return null;

  // Only the experimental model actually returns images
  const MODELS = ['gemini-2.0-flash-exp-image-generation'];

  for (const model of MODELS) {
    const key = rotateKey(keys, 'Gemini-image');
    if (!key) return null;
    onStatus({ message: `Trying Gemini image generation…`, provider: 'Gemini' });

    try {
      const res = await fetch(`${GEMINI_BASE}/${model}:generateContent?key=${key}`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(formatImageRequest(prompt))
      });

      if (!res.ok) {
        const action = classifyStatus(res.status);
        // IMPORTANT: Only throw safety for actual 400, not for other failures
        if (action === 'stop') {
          const errData = await res.json().catch(() => ({})) as { error?: { message?: string } };
          const msg = errData?.error?.message || '';
          // Only block if explicitly a safety issue
          if (msg.toLowerCase().includes('safety') || msg.toLowerCase().includes('block')) {
            throw new Error('SAFETY:Gemini blocked this prompt');
          }
          // 400 for other reasons = model doesn't support → return null
          return null;
        }
        if (res.status === 429) exhaustKey(key);
        return null; // Other errors → return null (don't throw)
      }

      const data = await res.json();
      console.log('[ImagePipeline] Gemini response:', JSON.stringify(data).slice(0, 300));

      // Check for safety block in response body
      if (data?.promptFeedback?.blockReason) {
        throw new Error(`SAFETY:${data.promptFeedback.blockReason}`);
      }

      const imgUrl   = extractImageData(data);
      const textDesc = extractImageText(data);

      console.log('[ImagePipeline] imgUrl exists:', !!imgUrl, 'textDesc length:', textDesc?.length);

      if (imgUrl) {
        recordSuccess('Gemini');
        return {
          success: true, imageUrl: imgUrl,
          description: textDesc || 'Image generated by Gemini AI',
          provider: 'Gemini', mode: 'generated',
          meta: { model }
        };
      }

      // Gemini returned text but no image — this is NOT an error, just means
      // the free tier doesn't support actual image generation
      // Return null so we fall through to text description
      if (textDesc) {
        console.log('[ImagePipeline] Gemini returned text-only (no image data)');
      }
      return null;

    } catch (err) {
      const msg = err instanceof Error ? err.message : '';
      if (msg.startsWith('SAFETY:')) throw err;
      return null;
    }
  }
  return null;
}

// ── 4. Text description fallback (always works) ──────────
function buildTextFallback(prompt: string): ImageResult {
  return {
    success: true,
    imageUrl: null,
    description: [
      `🎨 Image Concept: "${prompt}"`,
      '',
      '📐 Visual Description:',
      `A stunning, highly detailed composition depicting ${prompt}.`,
      'Cinematic lighting, rich contrast, vibrant colors, atmospheric and immersive.',
      '',
      '🖼️ Ready-to-use AI Art Prompts:',
      '',
      `📌 Midjourney:`,
      `/imagine prompt: ${prompt}, highly detailed, 8k, cinematic lighting, professional photography --ar 16:9 --v 6`,
      '',
      `📌 DALL-E 3:`,
      `Create a high-quality, photorealistic image of ${prompt} with dramatic lighting and ultra-detailed rendering.`,
      '',
      `📌 Stable Diffusion:`,
      `${prompt}, masterpiece, best quality, ultra detailed, photorealistic, 8k uhd, cinematic lighting`,
      '',
      '💡 Tip: Add Cloudflare Workers AI or HuggingFace API keys in your .env file for actual image generation.'
    ].join('\n'),
    provider: 'Text Description',
    mode: 'described',
    meta: { fallback: true }
  };
}

// ── MAIN EXPORT ───────────────────────────────────────────
export async function generateImageWithFallback(
  prompt:   string,
  onStatus: OnImageStatus = () => {}
): Promise<ImageResult> {

  onStatus({ message: 'Starting image generation…' });

  // Order: Cloudflare → HuggingFace → Gemini → text fallback
  const pipeline: Array<{ name: string; fn: () => Promise<ImageResult | null> }> = [
    { name: 'Cloudflare AI', fn: () => tryCloudflareImage(prompt, onStatus) },
    { name: 'HuggingFace',   fn: () => tryHuggingFaceImage(prompt, onStatus) },
    { name: 'Gemini',        fn: () => tryGeminiImage(prompt, onStatus) }
  ].filter(p =>
    p.name === 'Cloudflare AI' ? hasCloudflare() :
    p.name === 'HuggingFace'   ? hasHuggingFace() :
    p.name === 'Gemini'        ? hasGemini() : false
  );

  for (let i = 0; i < pipeline.length; i++) {
    if (i > 0) await backoff();
    const { name, fn } = pipeline[i];

    try {
      const result = await fn();
      if (result) return result;
      // null = provider couldn't produce image → try next
      if (i < pipeline.length - 1) {
        onStatus({ message: `${name} didn't return an image. Trying next provider…`, provider: name });
      }
    } catch (err) {
      const msg = err instanceof Error ? err.message : '';
      // Only propagate ACTUAL safety blocks, not other failures
      if (msg.startsWith('SAFETY:')) {
        throw new Error(msg.replace('SAFETY:', ''));
      }
      recordFailure(name);
      onStatus({ message: `${name} failed. Trying next…`, provider: name });
    }
  }

  // All image providers failed or not configured — return text description
  // This is NEVER a "safety policy" error
  onStatus({ message: 'Generating AI art prompts…' });
  return buildTextFallback(prompt);
}
